/**
 * Writes packages/nextjs/contracts/deployedContracts.ts from the committed deployment records and the
 * compiled ABIs, so the frontend's typed hooks know every contract on both chains.
 *
 *   npm run foundry:export
 */
import { writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { format } from "prettier";

import { readDeployment } from "./lib/deployments.js";
import { loadArtifact } from "./lib/session.js";

const CHAINS = [296, 84532];
const target = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "nextjs", "contracts", "deployedContracts.ts");

const declaration = {};
for (const chainId of CHAINS) {
  const deployment = readDeployment(chainId);
  if (!deployment) continue;
  declaration[chainId] = {};
  for (const [name, { address, blockNumber }] of Object.entries(deployment.contracts)) {
    declaration[chainId][name] = {
      address,
      abi: loadArtifact(name).abi,
      deployedOnBlock: Number(blockNumber),
    };
  }
}

if (Object.keys(declaration).length === 0) {
  throw new Error("No deployments found in packages/foundry/deployments. Deploy first.");
}

const source = `/**
 * Generated by \`npm run foundry:export\` from packages/foundry/deployments. Do not edit by hand.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = ${JSON.stringify(declaration, null, 2)} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
`;

writeFileSync(target, await format(source, { parser: "typescript", printWidth: 120 }));
console.log(`Wrote ${target} (chains: ${Object.keys(declaration).join(", ")})`);
