/**
 * Points the frontend at the compiled contracts and the committed deployment records. Writes three files
 * in packages/nextjs/contracts/:
 *
 * - abis.ts: every contract's ABI, typed `as const`, whether or not it is deployed yet;
 * - daoDeployment.ts: the addresses and chain settings the DAO pages read (Hedera is `null` until the
 *   DAO is deployed);
 * - deployedContracts.ts: the same contracts in Scaffold-HBAR's format, for the /debug page.
 *
 *   npm run foundry:export
 */
import { writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { format } from "prettier";

import { readDeployment } from "./lib/deployments.js";
import { getNetwork } from "./lib/networks.js";
import { loadArtifact } from "./lib/session.js";

const contractsDir = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "nextjs", "contracts");
const header = "/**\n * Generated by `npm run foundry:export`. Do not edit by hand.\n */\n";

const ABI_EXPORTS = {
  daoGovernorAbi: "DaoGovernor",
  daoTimelockAbi: "DaoTimelock",
  voteTokenAbi: "VoteToken",
  govTokenFaucetAbi: "GovTokenFaucet",
  crossChainExecutorAbi: "CrossChainExecutor",
  daoAccountAbi: "DaoAccount",
  remoteParametersAbi: "RemoteParameters",
};

async function write(file, source) {
  const path = join(contractsDir, file);
  writeFileSync(path, await format(source, { parser: "typescript", printWidth: 120 }));
  return path;
}

const hedera = getNetwork("hedera_testnet");
const base = getNetwork("base_sepolia");
const hederaDeployment = readDeployment(hedera.chain.id);
const baseDeployment = readDeployment(base.chain.id);
if (!baseDeployment?.contracts?.CrossChainExecutor) {
  throw new Error("No Base Sepolia deployment in packages/foundry/deployments/84532.json.");
}

// 1. ABIs
const abiSource = Object.entries(ABI_EXPORTS)
  .map(([name, contract]) => `export const ${name} = ${JSON.stringify(loadArtifact(contract).abi)} as const;`)
  .join("\n\n");
const written = [await write("abis.ts", `${header}\n${abiSource}\n`)];

// 2. DAO deployment settings
const timestampOf = (iso) => Math.floor(new Date(iso).getTime() / 1000);
const deployment = {
  hedera: hederaDeployment && {
    chainId: hedera.chain.id,
    mirrorNode: hedera.mirrorNode,
    ccipRouter: hedera.ccipRouter,
    ccipChainSelector: hedera.ccipChainSelector.toString(),
    deployedAt: timestampOf(hederaDeployment.deployedAt),
    deployer: hederaDeployment.deployer,
    governanceToken: hederaDeployment.governanceToken,
    governanceSymbol: hederaDeployment.settings.tokenSymbol,
    governor: hederaDeployment.contracts.DaoGovernor.address,
    timelock: hederaDeployment.contracts.DaoTimelock.address,
    voteToken: hederaDeployment.contracts.VoteToken.address,
    faucet: hederaDeployment.contracts.GovTokenFaucet.address,
    remoteAccount: hederaDeployment.remote.daoAccount,
  },
  base: {
    chainId: base.chain.id,
    ccipRouter: base.ccipRouter,
    ccipChainSelector: base.ccipChainSelector.toString(),
    executor: baseDeployment.contracts.CrossChainExecutor.address,
    remoteParameters: baseDeployment.contracts.RemoteParameters.address,
    usdc: base.usdc,
    deployedBlock: baseDeployment.contracts.CrossChainExecutor.blockNumber,
  },
};
written.push(
  await write(
    "daoDeployment.ts",
    `${header}
/** Chain selectors are decimal strings because they exceed Number.MAX_SAFE_INTEGER. */
const daoDeployment = ${JSON.stringify(deployment, null, 2)} as const;

export default daoDeployment;
`,
  ),
);

// 3. Scaffold-HBAR's contract declaration for /debug
const declaration = {};
for (const record of [hederaDeployment, baseDeployment]) {
  if (!record) continue;
  declaration[record.chainId] = {};
  for (const [name, { address, blockNumber }] of Object.entries(record.contracts)) {
    declaration[record.chainId][name] = {
      address,
      abi: loadArtifact(name).abi,
      deployedOnBlock: Number(blockNumber),
    };
  }
}
written.push(
  await write(
    "deployedContracts.ts",
    `${header}import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = ${JSON.stringify(declaration, null, 2)} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
`,
  ),
);

for (const path of written) console.log(`Wrote ${path}`);
console.log(
  hederaDeployment ? "Hedera DAO: exported." : "Hedera DAO: not deployed yet (daoDeployment.hedera is null).",
);
