/**
 * Generated by `npm run foundry:export`. Do not edit by hand.
 */

/** Chain selectors are decimal strings because they exceed Number.MAX_SAFE_INTEGER. */
const daoDeployment = {
  hedera: null,
  base: {
    chainId: 84532,
    ccipRouter: "0xD3b06cEbF099CE7DA4AcCf578aaebFDBd6e88a93",
    ccipChainSelector: "10344971235874465080",
    executor: "0x9b7691b0766a55d8509b07cb633ce281fee2a632",
    remoteParameters: "0x5f8b11a830ce09d87fa586c95e7c85fa57691cd9",
    usdc: "0x036CbD53842c5426634e7929541eC2318f3dCF7e",
    deployedBlock: "47557219",
  },
} as const;

export default daoDeployment;
