/**
 * Generated by `npm run foundry:export`. Do not edit by hand.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  "84532": {
    CrossChainExecutor: {
      address: "0x9b7691b0766a55d8509b07cb633ce281fee2a632",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "router",
              type: "address",
              internalType: "address",
            },
            {
              name: "receiptGasLimit_",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "sponsoredReceiptsPerDao_",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "accountImplementation",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "accountOf",
          inputs: [
            {
              name: "sourceChainSelector",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "sourceDao",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "ccipReceive",
          inputs: [
            {
              name: "message",
              type: "tuple",
              internalType: "struct Client.Any2EVMMessage",
              components: [
                {
                  name: "messageId",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "sourceChainSelector",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "sender",
                  type: "bytes",
                  internalType: "bytes",
                },
                {
                  name: "data",
                  type: "bytes",
                  internalType: "bytes",
                },
                {
                  name: "destTokenAmounts",
                  type: "tuple[]",
                  internalType: "struct Client.EVMTokenAmount[]",
                  components: [
                    {
                      name: "token",
                      type: "address",
                      internalType: "address",
                    },
                    {
                      name: "amount",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
              ],
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "ccipRouter",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "decodeRequest",
          inputs: [
            {
              name: "data",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct CrossChainMessages.Request",
              components: [
                {
                  name: "version",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "validUntil",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "calls",
                  type: "tuple[]",
                  internalType: "struct CrossChainMessages.Call[]",
                  components: [
                    {
                      name: "target",
                      type: "address",
                      internalType: "address",
                    },
                    {
                      name: "value",
                      type: "uint256",
                      internalType: "uint256",
                    },
                    {
                      name: "data",
                      type: "bytes",
                      internalType: "bytes",
                    },
                  ],
                },
              ],
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "receiptGasLimit",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "sponsoredReceiptsPerDao",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "sponsoredReceiptsUsed",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "count",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "statusOf",
          inputs: [
            {
              name: "messageId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "enum CrossChainMessages.Status",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "supportsInterface",
          inputs: [
            {
              name: "interfaceId",
              type: "bytes4",
              internalType: "bytes4",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "event",
          name: "AccountCreated",
          inputs: [
            {
              name: "account",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "sourceChain",
              type: "uint64",
              indexed: true,
              internalType: "uint64",
            },
            {
              name: "sourceDao",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ReceiptNotSent",
          inputs: [
            {
              name: "requestId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "fee",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "reason",
              type: "bytes",
              indexed: false,
              internalType: "bytes",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ReceiptSent",
          inputs: [
            {
              name: "requestId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "receiptMessageId",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "fee",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "paidBy",
              type: "uint8",
              indexed: false,
              internalType: "enum CrossChainExecutor.FeePayer",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "RequestProcessed",
          inputs: [
            {
              name: "messageId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "sourceChain",
              type: "uint64",
              indexed: true,
              internalType: "uint64",
            },
            {
              name: "sourceDao",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "account",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "status",
              type: "uint8",
              indexed: false,
              internalType: "enum CrossChainMessages.Status",
            },
            {
              name: "revertData",
              type: "bytes",
              indexed: false,
              internalType: "bytes",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Sponsored",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AlreadyProcessed",
          inputs: [
            {
              name: "messageId",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
        },
        {
          type: "error",
          name: "FailedDeployment",
          inputs: [],
        },
        {
          type: "error",
          name: "InsufficientBalance",
          inputs: [
            {
              name: "balance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "needed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "InvalidSender",
          inputs: [
            {
              name: "sender",
              type: "bytes",
              internalType: "bytes",
            },
          ],
        },
        {
          type: "error",
          name: "NotRouter",
          inputs: [
            {
              name: "caller",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ReceiptRefundFailed",
          inputs: [],
        },
        {
          type: "error",
          name: "ReceiptUnfunded",
          inputs: [],
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: [],
        },
        {
          type: "error",
          name: "SafeCastOverflowedUintDowncast",
          inputs: [
            {
              name: "bits",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "UnsupportedVersion",
          inputs: [
            {
              name: "version",
              type: "uint8",
              internalType: "uint8",
            },
          ],
        },
        {
          type: "error",
          name: "ZeroRouter",
          inputs: [],
        },
      ],
      deployedOnBlock: 47557219,
    },
    RemoteParameters: {
      address: "0x5f8b11a830ce09d87fa586c95e7c85fa57691cd9",
      abi: [
        {
          type: "function",
          name: "set",
          inputs: [
            {
              name: "key",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "updatedAt",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "key",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "timestamp",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "valueOf",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "key",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "ParameterSet",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "key",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "previous",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
      ],
      deployedOnBlock: 47557220,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
